/** Broad category a format falls into after parsing. */
export type FormatKind = 'merged' | 'video-only' | 'audio-only';

/** A raw format enriched by the parser with a computed quality score. */
export interface RankedFormat {
  formatId: string;
  ext: string;
  kind: FormatKind;
  resolution: string | null;
  height: number | null;
  fps: number | null;
  vcodec: string | null;
  acodec: string | null;
  tbr: number | null;
  isHdr: boolean;
  filesizeBytes: number | null;
  note: string | null;
  /** Higher is better; produced by the quality ranking engine. */
  score: number;
}

/** A subtitle track available for a media item. */
export interface SubtitleTrack {
  language: string;
  ext: string | null;
  autoGenerated: boolean;
}

/** Rich, parsed metadata ready for the UI. */
export interface RichMetadata {
  title: string;
  description: string | null;
  durationSeconds: number | null;
  uploader: string | null;
  channel: string | null;
  thumbnail: string | null;
  uploadDate: string | null;
  viewCount: number | null;
  likeCount: number | null;
  isLive: boolean;
  ageLimit: number | null;
  isPlaylist: boolean;
  formats: RankedFormat[];
  subtitles: SubtitleTrack[];
  source: string;
}

/** Preferences that steer automatic quality ranking. */
export interface RankingPreferences {
  /** Prefer higher frame rate when resolutions tie. */
  preferHighFps: boolean;
  /** Prefer smaller files (inverts the size contribution). */
  preferSmallSize: boolean;
  /** Preferred video codec substring, e.g. `'av01'` or `'vp9'`. */
  preferredCodec: string | null;
}
