import type {
  AudioFormat,
  DownloadOptions,
  VideoContainer,
} from '../types/options.types';

/** Sensible defaults: best quality video, no extra processing. */
export const DEFAULT_OPTIONS: DownloadOptions = {
  mode: 'video',
  quality: 'best',
  formatId: null,
  videoContainer: 'mp4',
  audioFormat: 'mp3',
  audioBitrateKbps: null,
  rateLimit: null,
  proxy: null,
  timeoutSeconds: null,
  verbose: false,
  maxConcurrent: 3,
  downloadThumbnail: false,
  embedThumbnail: false,
  embedMetadata: true,
  outputTemplate: null,
  subtitles: {
    download: false,
    embed: false,
    includeAutoGenerated: false,
    languages: [],
  },
  playlist: {
    enabled: false,
    maxItems: null,
    skipExisting: true,
    reverse: false,
  },
  cookies: {
    cookieFile: null,
    fromBrowser: null,
  },
  retry: {
    maxAttempts: 2,
    baseDelayMs: 2000,
  },
};

/** Containers offered in the UI, most useful first. */
export const VIDEO_CONTAINERS: VideoContainer[] = ['mp4', 'mkv', 'webm', 'mov', 'avi'];

/** Audio formats offered in the UI, most useful first. */
export const AUDIO_FORMATS: AudioFormat[] = ['mp3', 'm4a', 'opus', 'flac', 'aac', 'wav', 'vorbis'];

/** Bitrate choices (kbps) for audio extraction. */
export const AUDIO_BITRATES = [128, 192, 256, 320];

/** Browsers yt-dlp can read cookies from. */
export const COOKIE_BROWSERS = ['firefox', 'chrome', 'chromium', 'edge', 'safari', 'brave'];

/** The default output template when the user hasn't set one. */
export const DEFAULT_OUTPUT_TEMPLATE = '%(title)s.%(ext)s';

/** Template used for playlist downloads when none is specified. */
export const PLAYLIST_OUTPUT_TEMPLATE =
  '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s';
