/** Lifecycle states a download moves through. */
export type DownloadStatus =
  | 'idle'
  | 'probing'
  | 'ready'
  | 'queued'
  | 'downloading'
  | 'paused'
  | 'done'
  | 'cancelled'
  | 'error';

/** A single selectable format for a media URL. */
export interface MediaFormat {
  formatId: string;
  ext: string;
  resolution: string | null;
  height: number | null;
  fps: number | null;
  vcodec: string | null;
  acodec: string | null;
  tbr: number | null;
  dynamicRange: string | null;
  filesizeBytes: number | null;
  note: string | null;
  hasVideo: boolean;
  hasAudio: boolean;
}

/** A subtitle track available for a media item. */
export interface SubtitleTrack {
  language: string;
  ext: string | null;
  autoGenerated: boolean;
}

/** Metadata resolved from a media URL before downloading. */
export interface MediaInfo {
  title: string;
  description: string | null;
  durationSeconds: number | null;
  uploader: string | null;
  channel: string | null;
  thumbnail: string | null;
  uploadDate: string | null;
  viewCount: number | null;
  likeCount: number | null;
  isLive: boolean;
  ageLimit: number | null;
  isPlaylist: boolean;
  formats: MediaFormat[];
  subtitles: SubtitleTrack[];
  source: string;
}

/** A single progress tick received from the backend during a download. */
export interface ProgressUpdate {
  id: string;
  percent: number;
  downloadedBytes: number;
  totalBytes: number;
  speed: string | null;
  eta: string | null;
}

import type { RichMetadata } from '@/modules/metadata';

/** A single download entry tracked in the store. */
export interface DownloadItem {
  id: string;
  url: string;
  status: DownloadStatus;
  progress: number;
  downloadedBytes: number;
  totalBytes: number;
  speed: string | null;
  eta: string | null;
  info: RichMetadata | null;
  selectedFormatId: string | null;
  outputDir: string | null;
  filePath: string | null;
  error: string | null;
  createdAt: number;
}
