/** Container the final video file should use. */
export type VideoContainer = 'mp4' | 'webm' | 'mkv' | 'mov' | 'avi';

/** Audio format used when extracting audio. */
export type AudioFormat = 'mp3' | 'm4a' | 'aac' | 'flac' | 'opus' | 'wav' | 'vorbis';

/** What kind of output the user wants. */
export type DownloadMode = 'video' | 'audio';

/** Quality shortcut applied when no explicit format id is chosen. */
export type QualityPreset = 'best' | 'best-compatible' | 'smallest' | 'custom';

/** Subtitle handling for a download. */
export interface SubtitleOptions {
  /** Download subtitle files alongside the media. */
  download: boolean;
  /** Burn/embed subtitles into the media container when supported. */
  embed: boolean;
  /** Include machine-generated captions. */
  includeAutoGenerated: boolean;
  /** Language codes to fetch, e.g. `['en', 'ca']`. Empty means all available. */
  languages: string[];
}

/** Playlist handling for a download. */
export interface PlaylistOptions {
  /** Treat a playlist URL as a playlist rather than a single item. */
  enabled: boolean;
  /** Stop after this many items. `null` means no limit. */
  maxItems: number | null;
  /** Skip items whose output file already exists. */
  skipExisting: boolean;
  /** Reverse the playlist order. */
  reverse: boolean;
}

/** Authentication material for sites that require a session. */
export interface CookieOptions {
  /** Absolute path to a Netscape-format cookies.txt file. */
  cookieFile: string | null;
  /** Browser to read cookies from, e.g. `'firefox'`. */
  fromBrowser: string | null;
}

/** Retry behaviour for failed downloads. */
export interface RetryOptions {
  /** Maximum automatic attempts after the first failure. */
  maxAttempts: number;
  /** Base delay in milliseconds; grows exponentially per attempt. */
  baseDelayMs: number;
}

/** The full set of options controlling one download. */
export interface DownloadOptions {
  mode: DownloadMode;
  quality: QualityPreset;
  /** Explicit yt-dlp format id; overrides `quality` when set. */
  formatId: string | null;
  videoContainer: VideoContainer;
  audioFormat: AudioFormat;
  /** Audio bitrate in kbps; `null` uses the source bitrate. */
  audioBitrateKbps: number | null;
  /** Cap the download rate, e.g. `'2M'`. `null` means unlimited. */
  rateLimit: string | null;
  /** Proxy URL passed to the provider. `null` means direct connection. */
  proxy: string | null;
  /** Socket timeout in seconds. `null` uses the provider default. */
  timeoutSeconds: number | null;
  /** Ask the provider for verbose output. */
  verbose: boolean;
  /** How many downloads may run at once. */
  maxConcurrent: number;
  /** Save the thumbnail as a separate file. */
  downloadThumbnail: boolean;
  /** Embed the thumbnail as cover art. */
  embedThumbnail: boolean;
  /** Write title/artist/date tags into the file. */
  embedMetadata: boolean;
  /** Custom yt-dlp output template; `null` uses the default. */
  outputTemplate: string | null;
  subtitles: SubtitleOptions;
  playlist: PlaylistOptions;
  cookies: CookieOptions;
  retry: RetryOptions;
}
