import type { DownloadOptions } from '@/modules/advanced';
import type { RankingPreferences } from '@/modules/metadata';
import type { Settings } from '../types/settings.types';

/**
 * Projects user settings onto the download options the queue consumes.
 *
 * This is the bridge that makes settings take effect: everything the user
 * configures ends up here and flows into the yt-dlp argument builder. Pure, so
 * the mapping is easy to verify in tests.
 */
export function settingsToDownloadOptions(
  settings: Settings,
  base: DownloadOptions,
): DownloadOptions {
  return {
    ...base,
    quality: settings.video.quality,
    videoContainer: settings.video.container,
    audioFormat: settings.audio.format,
    audioBitrateKbps: settings.audio.bitrateKbps,
    embedMetadata: settings.audio.embedMetadata,
    embedThumbnail: settings.audio.embedThumbnail,
    rateLimit: settings.network.rateLimit || null,
    proxy: settings.network.proxy || null,
    timeoutSeconds: settings.network.timeoutSeconds,
    verbose: settings.advanced.verboseLogs,
    maxConcurrent: settings.performance.maxConcurrent,
    outputTemplate: settings.downloads.outputTemplate || null,
    subtitles: {
      download: settings.subtitles.download,
      embed: settings.subtitles.embed,
      includeAutoGenerated: settings.subtitles.includeAutoGenerated,
      languages: settings.subtitles.languages,
    },
    playlist: {
      ...base.playlist,
      skipExisting: settings.downloads.skipExisting,
    },
    cookies: {
      cookieFile: settings.privacy.cookieFile || null,
      fromBrowser: settings.privacy.cookieBrowser || null,
    },
    retry: {
      maxAttempts: settings.network.retryAttempts,
      baseDelayMs: settings.network.retryDelayMs,
    },
  };
}

/**
 * Projects video settings onto the metadata ranking preferences, so the
 * format list is ordered the way the user asked for.
 */
export function settingsToRankingPreferences(settings: Settings): RankingPreferences {
  return {
    preferHighFps: settings.video.preferHighFps,
    preferSmallSize: false,
    preferredCodec: settings.video.preferredCodec,
  };
}
