import type { SettingsSection } from '../types/settings.types';

/** One searchable setting entry. */
export interface SettingEntry {
  section: SettingsSection;
  /** Dotted path, e.g. `network.proxy`. */
  path: string;
  label: string;
  /** Extra terms that should match this entry. */
  keywords: string[];
}

/** Display names for each section, used in the sidebar and search results. */
export const SECTION_LABELS: Record<SettingsSection, string> = {
  downloads: 'Downloads',
  video: 'Video',
  audio: 'Audio',
  subtitles: 'Subtitles',
  appearance: 'Appearance',
  notifications: 'Notifications',
  performance: 'Performance',
  history: 'History',
  network: 'Network',
  privacy: 'Privacy',
  desktop: 'Desktop',
  advanced: 'Advanced',
};

/**
 * The searchable catalogue of settings. Every control rendered in the UI has an
 * entry here so search can find it; adding a setting means adding a row.
 */
export const SETTINGS_INDEX: SettingEntry[] = [
  { section: 'downloads', path: 'downloads.defaultFolder', label: 'Default download folder', keywords: ['folder', 'destination', 'path', 'output'] },
  { section: 'downloads', path: 'downloads.alwaysAsk', label: 'Always ask where to save', keywords: ['prompt', 'destination', 'ask'] },
  { section: 'downloads', path: 'downloads.skipExisting', label: 'Skip existing files', keywords: ['duplicate', 'skip'] },
  { section: 'downloads', path: 'downloads.overwrite', label: 'Overwrite existing files', keywords: ['replace', 'duplicate'] },
  { section: 'downloads', path: 'downloads.outputTemplate', label: 'Filename template', keywords: ['name', 'pattern', 'template'] },

  { section: 'video', path: 'video.quality', label: 'Preferred quality', keywords: ['quality', 'best', 'compatible'] },
  { section: 'video', path: 'video.container', label: 'Preferred container', keywords: ['mp4', 'mkv', 'webm', 'format'] },
  { section: 'video', path: 'video.maxHeight', label: 'Maximum resolution', keywords: ['1080', '4k', 'resolution', 'height'] },
  { section: 'video', path: 'video.preferredCodec', label: 'Preferred codec', keywords: ['av1', 'vp9', 'h264', 'codec'] },
  { section: 'video', path: 'video.preferHdr', label: 'Prefer HDR', keywords: ['hdr', 'dynamic range'] },
  { section: 'video', path: 'video.preferHighFps', label: 'Prefer high frame rate', keywords: ['fps', 'frame rate', '60'] },

  { section: 'audio', path: 'audio.format', label: 'Audio format', keywords: ['mp3', 'flac', 'opus', 'm4a'] },
  { section: 'audio', path: 'audio.bitrateKbps', label: 'Audio bitrate', keywords: ['bitrate', 'kbps', 'quality'] },
  { section: 'audio', path: 'audio.embedMetadata', label: 'Embed metadata', keywords: ['tags', 'metadata', 'id3'] },
  { section: 'audio', path: 'audio.embedThumbnail', label: 'Embed thumbnail', keywords: ['cover', 'art', 'thumbnail'] },

  { section: 'subtitles', path: 'subtitles.download', label: 'Download subtitles', keywords: ['subtitle', 'captions', 'srt'] },
  { section: 'subtitles', path: 'subtitles.embed', label: 'Embed subtitles', keywords: ['subtitle', 'burn', 'embed'] },
  { section: 'subtitles', path: 'subtitles.includeAutoGenerated', label: 'Auto-generated captions', keywords: ['auto', 'captions', 'generated'] },
  { section: 'subtitles', path: 'subtitles.languages', label: 'Subtitle languages', keywords: ['language', 'subtitle', 'lang'] },

  { section: 'appearance', path: 'appearance.theme', label: 'Theme', keywords: ['dark', 'light', 'system', 'theme'] },
  { section: 'appearance', path: 'appearance.density', label: 'Interface density', keywords: ['compact', 'density', 'spacing'] },
  { section: 'appearance', path: 'appearance.reduceMotion', label: 'Reduce motion', keywords: ['animation', 'motion', 'accessibility'] },

  { section: 'notifications', path: 'notifications.onComplete', label: 'Notify on completion', keywords: ['notification', 'desktop', 'alert', 'complete'] },
  { section: 'notifications', path: 'notifications.onFailure', label: 'Notify on failure', keywords: ['notification', 'desktop', 'alert', 'error'] },

  { section: 'performance', path: 'performance.maxConcurrent', label: 'Simultaneous downloads', keywords: ['concurrent', 'parallel', 'queue'] },
  { section: 'performance', path: 'performance.metadataCacheTtlMinutes', label: 'Metadata cache lifetime', keywords: ['cache', 'ttl', 'metadata'] },

  { section: 'history', path: 'history.enabled', label: 'Keep history', keywords: ['history', 'record'] },
  { section: 'history', path: 'history.maxEntries', label: 'Maximum history entries', keywords: ['history', 'limit', 'entries'] },

  { section: 'network', path: 'network.proxy', label: 'Proxy', keywords: ['proxy', 'socks', 'http'] },
  { section: 'network', path: 'network.timeoutSeconds', label: 'Timeout', keywords: ['timeout', 'seconds'] },
  { section: 'network', path: 'network.rateLimit', label: 'Bandwidth limit', keywords: ['speed', 'rate', 'bandwidth', 'limit'] },
  { section: 'network', path: 'network.retryAttempts', label: 'Retry attempts', keywords: ['retry', 'attempts'] },
  { section: 'network', path: 'network.retryDelayMs', label: 'Retry delay', keywords: ['retry', 'delay', 'backoff'] },

  { section: 'privacy', path: 'privacy.cookieBrowser', label: 'Cookies from browser', keywords: ['cookie', 'login', 'session', 'browser'] },
  { section: 'privacy', path: 'privacy.cookieFile', label: 'Cookie file', keywords: ['cookie', 'txt', 'netscape'] },

  { section: 'desktop', path: 'desktop.launchAtStartup', label: 'Launch at startup', keywords: ['startup', 'autostart', 'boot', 'login'] },
  { section: 'desktop', path: 'desktop.startMinimized', label: 'Start minimized', keywords: ['minimized', 'tray', 'hidden'] },
  { section: 'desktop', path: 'desktop.minimizeToTray', label: 'Minimize to tray on close', keywords: ['tray', 'close', 'background'] },
  { section: 'desktop', path: 'desktop.clipboardMonitor', label: 'Watch clipboard for links', keywords: ['clipboard', 'copy', 'paste', 'monitor'] },
  { section: 'desktop', path: 'desktop.rememberWindowState', label: 'Remember window size and position', keywords: ['window', 'size', 'position', 'restore'] },

  { section: 'advanced', path: 'advanced.ytDlpPath', label: 'Custom yt-dlp path', keywords: ['yt-dlp', 'binary', 'executable', 'path'] },
  { section: 'advanced', path: 'advanced.ffmpegPath', label: 'Custom FFmpeg path', keywords: ['ffmpeg', 'binary', 'executable', 'path'] },
  { section: 'advanced', path: 'advanced.verboseLogs', label: 'Verbose logs', keywords: ['debug', 'log', 'verbose'] },
  { section: 'advanced', path: 'advanced.debugMode', label: 'Debug mode', keywords: ['debug', 'diagnostics', 'log'] },
];

/**
 * Finds settings matching a query across label, keywords and section name.
 * Returns everything when the query is empty. Pure — safe to call per render.
 */
export function searchSettings(query: string): SettingEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return SETTINGS_INDEX;

  return SETTINGS_INDEX.filter((entry) => {
    const haystack = [
      entry.label,
      SECTION_LABELS[entry.section],
      ...entry.keywords,
    ]
      .join(' ')
      .toLowerCase();
    return haystack.includes(q);
  });
}

/** Returns the sections that contain at least one match for a query. */
export function matchingSections(query: string): SettingsSection[] {
  const sections = new Set(searchSettings(query).map((e) => e.section));
  return [...sections];
}
