import type {
  AudioFormat,
  QualityPreset,
  VideoContainer,
} from '@/modules/advanced';

/** Theme preference; `system` follows the OS setting. */
export type ThemePreference = 'dark' | 'light' | 'system';

/** Interface density affecting spacing and control sizes. */
export type Density = 'comfortable' | 'compact';

/** Where completed files go and how they are named. */
export interface DownloadSettings {
  /** Default output folder. Empty means ask every time. */
  defaultFolder: string;
  /** Ask for a destination on every download, ignoring `defaultFolder`. */
  alwaysAsk: boolean;
  /** Skip items whose output file already exists. */
  skipExisting: boolean;
  /** Overwrite instead of skipping when a file exists. */
  overwrite: boolean;
  /** Custom yt-dlp output template; empty uses the default. */
  outputTemplate: string;
}

/** Video preferences fed into format ranking and container selection. */
export interface VideoSettings {
  quality: QualityPreset;
  container: VideoContainer;
  /** Preferred max height, e.g. 1080. `null` means no cap. */
  maxHeight: number | null;
  /** Preferred video codec substring, e.g. `'av01'`. */
  preferredCodec: string | null;
  /** Rank HDR formats above SDR. */
  preferHdr: boolean;
  /** Prefer higher frame rates when quality ties. */
  preferHighFps: boolean;
}

/** Audio preferences applied when extracting audio. */
export interface AudioSettings {
  format: AudioFormat;
  /** Bitrate in kbps; `null` keeps the source bitrate. */
  bitrateKbps: number | null;
  embedMetadata: boolean;
  embedThumbnail: boolean;
}

/** Subtitle preferences. */
export interface SubtitleSettings {
  download: boolean;
  embed: boolean;
  includeAutoGenerated: boolean;
  /** Preferred language codes; empty means all available. */
  languages: string[];
}

/** Visual preferences. */
export interface AppearanceSettings {
  theme: ThemePreference;
  density: Density;
  /** Disable non-essential animation regardless of OS setting. */
  reduceMotion: boolean;
}

/** Desktop notification preferences. */
export interface NotificationSettings {
  /** Show a native OS notification when a download finishes. */
  onComplete: boolean;
  /** Show one when a download fails. */
  onFailure: boolean;
}

/** Queue and cache tuning. */
export interface PerformanceSettings {
  maxConcurrent: number;
  /** Metadata cache lifetime in minutes. */
  metadataCacheTtlMinutes: number;
}

/** History retention. */
export interface HistorySettings {
  enabled: boolean;
  /** Maximum entries kept; older ones are trimmed. */
  maxEntries: number;
}

/** Network behaviour passed to the download provider. */
export interface NetworkSettings {
  /** Proxy URL, e.g. `http://127.0.0.1:8080`. Empty means none. */
  proxy: string;
  /** Socket timeout in seconds. */
  timeoutSeconds: number;
  /** Rate cap such as `2M`. Empty means unlimited. */
  rateLimit: string;
  retryAttempts: number;
  retryDelayMs: number;
}

/** Session and cookie handling. */
export interface PrivacySettings {
  /** Browser to read cookies from; empty means none. */
  cookieBrowser: string;
  /** Path to a Netscape cookies.txt file; empty means none. */
  cookieFile: string;
}

/** Desktop integration behaviour. */
export interface DesktopSettings {
  /** Launch the app when the OS starts. */
  launchAtStartup: boolean;
  /** Start hidden in the tray rather than showing the window. */
  startMinimized: boolean;
  /** Closing the window hides to tray instead of quitting. */
  minimizeToTray: boolean;
  /** Watch the clipboard for URLs and offer a quick download. */
  clipboardMonitor: boolean;
  /** Restore window size and position between sessions. */
  rememberWindowState: boolean;
}

/** Power-user overrides. */
export interface AdvancedSettings {
  /** Custom yt-dlp executable path; empty uses PATH. */
  ytDlpPath: string;
  /** Custom ffmpeg executable path; empty uses PATH. */
  ffmpegPath: string;
  /** Pass `--verbose` to the provider and log more. */
  verboseLogs: boolean;
  /** Record debug-level entries in the application log. */
  debugMode: boolean;
}

/** The complete, versioned settings document. */
export interface Settings {
  /** Schema version, used for migration on load. */
  version: number;
  downloads: DownloadSettings;
  video: VideoSettings;
  audio: AudioSettings;
  subtitles: SubtitleSettings;
  appearance: AppearanceSettings;
  notifications: NotificationSettings;
  performance: PerformanceSettings;
  history: HistorySettings;
  network: NetworkSettings;
  privacy: PrivacySettings;
  desktop: DesktopSettings;
  advanced: AdvancedSettings;
}

/** Top-level setting groups, used for navigation and reset. */
export type SettingsSection = Exclude<keyof Settings, 'version'>;
