import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import type {
  MediaFormat,
  MediaInfo,
  ProgressUpdate,
  SubtitleTrack,
} from '../types/download.types';
import type { DownloadPhase, LogLevel, PhaseUpdate } from '../types/live.types';

interface RawFormat {
  format_id: string;
  ext: string;
  resolution: string | null;
  height: number | null;
  fps: number | null;
  vcodec: string | null;
  acodec: string | null;
  tbr: number | null;
  dynamic_range: string | null;
  filesize_bytes: number | null;
  note: string | null;
  has_video: boolean;
  has_audio: boolean;
}

interface RawSubtitle {
  language: string;
  ext: string | null;
  auto_generated: boolean;
}

interface RawMediaInfo {
  title: string;
  description: string | null;
  duration_seconds: number | null;
  uploader: string | null;
  channel: string | null;
  thumbnail: string | null;
  upload_date: string | null;
  view_count: number | null;
  like_count: number | null;
  is_live: boolean;
  age_limit: number | null;
  is_playlist: boolean;
  formats: RawFormat[];
  subtitles: RawSubtitle[];
  source: string;
}

function mapFormat(raw: RawFormat): MediaFormat {
  return {
    formatId: raw.format_id,
    ext: raw.ext,
    resolution: raw.resolution,
    height: raw.height,
    fps: raw.fps,
    vcodec: raw.vcodec,
    acodec: raw.acodec,
    tbr: raw.tbr,
    dynamicRange: raw.dynamic_range,
    filesizeBytes: raw.filesize_bytes,
    note: raw.note,
    hasVideo: raw.has_video,
    hasAudio: raw.has_audio,
  };
}

function mapSubtitle(raw: RawSubtitle): SubtitleTrack {
  return {
    language: raw.language,
    ext: raw.ext,
    autoGenerated: raw.auto_generated,
  };
}

/**
 * Resolves metadata and available formats for a media URL via the Rust
 * `probe_media` command. Throws with a readable message on failure.
 */
export async function probeMedia(url: string, ytDlpPath = ''): Promise<MediaInfo> {
  let raw: RawMediaInfo;
  try {
    raw = await invoke<RawMediaInfo>('probe_media', { url, ytDlpPath });
  } catch (cause) {
    // Tauri rejects with the command's `Err(String)` value, which is a plain
    // string — not an Error. Wrap it so the real yt-dlp message survives the
    // trip to the UI instead of being replaced by a generic fallback.
    throw new Error(typeof cause === 'string' ? cause : String(cause));
  }
  return {
    title: raw.title,
    description: raw.description,
    durationSeconds: raw.duration_seconds,
    uploader: raw.uploader,
    channel: raw.channel,
    thumbnail: raw.thumbnail,
    uploadDate: raw.upload_date,
    viewCount: raw.view_count,
    likeCount: raw.like_count,
    isLive: raw.is_live,
    ageLimit: raw.age_limit,
    isPlaylist: raw.is_playlist,
    formats: raw.formats.map(mapFormat),
    subtitles: raw.subtitles.map(mapSubtitle),
    source: raw.source,
  };
}

/**
 * Starts downloading a media URL into `outputDir`. `extraArgs` carries the
 * caller's yt-dlp options (format, audio, subtitles, playlist, cookies) and
 * `outputTemplate` the filename pattern. Resolves when finished; rejects with
 * the backend error on failure.
 */
export async function downloadMedia(
  id: string,
  url: string,
  extraArgs: string[],
  outputTemplate: string,
  outputDir: string,
  binaries: { ytDlpPath: string; ffmpegPath: string } = { ytDlpPath: '', ffmpegPath: '' },
): Promise<string | null> {
  try {
    const path = await invoke<string | null>('download_media', {
      id,
      url,
      extraArgs,
      outputTemplate,
      outputDir,
      ytDlpPath: binaries.ytDlpPath,
      ffmpegPath: binaries.ffmpegPath,
    });
    return path ?? null;
  } catch (cause) {
    // Preserve the backend's real error string (a plain string from Rust's
    // Err), which would otherwise be lost as a non-Error rejection.
    throw new Error(typeof cause === 'string' ? cause : String(cause));
  }
}

/**
 * Stops an active download by killing its process (used for pause and cancel).
 * A partial file remains so a later resume can continue it. Resolves even if
 * the download already finished.
 */
export async function stopDownload(id: string): Promise<void> {
  await invoke('stop_download', { id });
}

/** Opens a file or folder in the OS default handler. */
export async function openPath(path: string): Promise<void> {
  await invoke('open_path', { path });
}

interface RawProgressUpdate {
  id: string;
  percent: number;
  downloaded_bytes: number;
  total_bytes: number;
  speed: string | null;
  eta: string | null;
}

/**
 * Subscribes to backend progress events. The returned function unsubscribes
 * and must be called on cleanup to avoid leaking listeners.
 */
export async function onProgress(
  handler: (update: ProgressUpdate) => void,
): Promise<UnlistenFn> {
  return listen<RawProgressUpdate>('download://progress', (event) => {
    const p = event.payload;
    handler({
      id: p.id,
      percent: p.percent,
      downloadedBytes: p.downloaded_bytes,
      totalBytes: p.total_bytes,
      speed: p.speed,
      eta: p.eta,
    });
  });
}

interface RawPhase {
  id: string;
  phase: string;
  detail: string;
}

interface RawLog {
  id: string;
  level: string;
  message: string;
}

/**
 * Subscribes to pipeline phase changes (merging, extracting audio, …). The
 * returned function unsubscribes and must be called on cleanup.
 */
export async function onPhase(
  handler: (update: PhaseUpdate) => void,
): Promise<UnlistenFn> {
  return listen<RawPhase>('download://phase', (event) => {
    handler({
      id: event.payload.id,
      phase: event.payload.phase as DownloadPhase,
      detail: event.payload.detail,
    });
  });
}

/**
 * Subscribes to raw provider output lines for the per-download live log. The
 * returned function unsubscribes and must be called on cleanup.
 */
export async function onLog(
  handler: (id: string, level: LogLevel, message: string) => void,
): Promise<UnlistenFn> {
  return listen<RawLog>('download://log', (event) => {
    handler(event.payload.id, event.payload.level as LogLevel, event.payload.message);
  });
}
