import type { Settings } from '../types/settings.types';

/**
 * Current settings schema version. Bump this whenever the shape changes and
 * add a matching step in `migrateSettings`.
 */
export const SETTINGS_VERSION = 1;

/** Factory defaults for every section. */
export const DEFAULT_SETTINGS: Settings = {
  version: SETTINGS_VERSION,
  downloads: {
    defaultFolder: '',
    alwaysAsk: true,
    skipExisting: true,
    overwrite: false,
    outputTemplate: '',
  },
  video: {
    quality: 'best',
    container: 'mp4',
    maxHeight: null,
    preferredCodec: null,
    preferHdr: true,
    preferHighFps: false,
  },
  audio: {
    format: 'mp3',
    bitrateKbps: null,
    embedMetadata: true,
    embedThumbnail: false,
  },
  subtitles: {
    download: false,
    embed: false,
    includeAutoGenerated: false,
    languages: [],
  },
  appearance: {
    theme: 'dark',
    density: 'comfortable',
    reduceMotion: false,
  },
  notifications: {
    onComplete: true,
    onFailure: true,
  },
  performance: {
    maxConcurrent: 3,
    metadataCacheTtlMinutes: 10,
  },
  history: {
    enabled: true,
    maxEntries: 500,
  },
  network: {
    proxy: '',
    timeoutSeconds: 30,
    rateLimit: '',
    retryAttempts: 2,
    retryDelayMs: 2000,
  },
  privacy: {
    cookieBrowser: '',
    cookieFile: '',
  },
  desktop: {
    launchAtStartup: false,
    startMinimized: false,
    minimizeToTray: true,
    clipboardMonitor: false,
    rememberWindowState: true,
  },
  advanced: {
    ytDlpPath: '',
    ffmpegPath: '',
    verboseLogs: false,
    debugMode: false,
  },
};

/** Resolutions offered as a maximum-height cap. */
export const RESOLUTION_CHOICES = [
  { value: null, label: 'No limit' },
  { value: 2160, label: '4K (2160p)' },
  { value: 1440, label: '1440p' },
  { value: 1080, label: '1080p' },
  { value: 720, label: '720p' },
  { value: 480, label: '480p' },
];

/** Video codecs the ranking engine understands. */
export const CODEC_CHOICES = [
  { value: null, label: 'Any' },
  { value: 'av01', label: 'AV1' },
  { value: 'vp9', label: 'VP9' },
  { value: 'avc1', label: 'H.264' },
];
