import { describe, it, expect } from 'vitest';
import { buildDownloadArgs, resolveOutputTemplate } from '../args-builder';
import { DEFAULT_OPTIONS, PLAYLIST_OUTPUT_TEMPLATE, DEFAULT_OUTPUT_TEMPLATE } from '../../constants/defaults';
import type { DownloadOptions } from '../../types/options.types';

function opts(overrides: Partial<DownloadOptions> = {}): DownloadOptions {
  return { ...DEFAULT_OPTIONS, ...overrides };
}

describe('buildDownloadArgs', () => {
  it('uses an explicit format id over the quality preset', () => {
    const args = buildDownloadArgs(opts({ formatId: '137' }));
    expect(args).toContain('-f');
    expect(args[args.indexOf('-f') + 1]).toBe('137');
  });

  it('picks a compatible selector for best-compatible', () => {
    const args = buildDownloadArgs(opts({ quality: 'best-compatible' }));
    const selector = args[args.indexOf('-f') + 1];
    expect(selector).toContain('avc1');
  });

  it('adds audio extraction flags in audio mode', () => {
    const args = buildDownloadArgs(opts({ mode: 'audio', audioFormat: 'flac' }));
    expect(args).toContain('-x');
    expect(args).toContain('--audio-format');
    expect(args[args.indexOf('--audio-format') + 1]).toBe('flac');
  });

  it('includes bitrate only when set', () => {
    expect(buildDownloadArgs(opts({ mode: 'audio' }))).not.toContain('--audio-quality');
    const args = buildDownloadArgs(opts({ mode: 'audio', audioBitrateKbps: 320 }));
    expect(args[args.indexOf('--audio-quality') + 1]).toBe('320K');
  });

  it('disables playlists by default and enables them on request', () => {
    expect(buildDownloadArgs(opts())).toContain('--no-playlist');
    const args = buildDownloadArgs(
      opts({ playlist: { ...DEFAULT_OPTIONS.playlist, enabled: true, maxItems: 5 } }),
    );
    expect(args).toContain('--yes-playlist');
    expect(args[args.indexOf('--playlist-end') + 1]).toBe('5');
  });

  it('adds subtitle flags only when requested', () => {
    expect(buildDownloadArgs(opts())).not.toContain('--write-subs');
    const args = buildDownloadArgs(
      opts({
        subtitles: { download: true, embed: true, includeAutoGenerated: true, languages: ['en', 'ca'] },
      }),
    );
    expect(args).toContain('--write-subs');
    expect(args).toContain('--embed-subs');
    expect(args).toContain('--write-auto-subs');
    expect(args[args.indexOf('--sub-langs') + 1]).toBe('en,ca');
  });

  it('prefers a cookie file over a browser profile', () => {
    const args = buildDownloadArgs(
      opts({ cookies: { cookieFile: '/tmp/c.txt', fromBrowser: 'firefox' } }),
    );
    expect(args).toContain('--cookies');
    expect(args).not.toContain('--cookies-from-browser');
  });

  it('adds a rate limit when configured', () => {
    expect(buildDownloadArgs(opts())).not.toContain('--limit-rate');
    const args = buildDownloadArgs(opts({ rateLimit: '2M' }));
    expect(args[args.indexOf('--limit-rate') + 1]).toBe('2M');
  });

  it('is deterministic for the same options', () => {
    expect(buildDownloadArgs(opts())).toEqual(buildDownloadArgs(opts()));
  });
});

describe('resolveOutputTemplate', () => {
  it('uses the default template for single downloads', () => {
    expect(resolveOutputTemplate(opts())).toBe(DEFAULT_OUTPUT_TEMPLATE);
  });

  it('uses the playlist template when playlists are enabled', () => {
    const result = resolveOutputTemplate(
      opts({ playlist: { ...DEFAULT_OPTIONS.playlist, enabled: true } }),
    );
    expect(result).toBe(PLAYLIST_OUTPUT_TEMPLATE);
  });

  it('respects a custom template', () => {
    expect(resolveOutputTemplate(opts({ outputTemplate: '%(id)s.%(ext)s' }))).toBe(
      '%(id)s.%(ext)s',
    );
  });
});
