import type { DownloadOptions } from '../types/options.types';
import { DEFAULT_OUTPUT_TEMPLATE, PLAYLIST_OUTPUT_TEMPLATE } from '../constants/defaults';

/**
 * Maps a quality preset to a yt-dlp format selector.
 *
 * `best-compatible` prefers H.264 + AAC in an MP4 container, which plays
 * everywhere; `best` takes the highest quality regardless of codec.
 */
function formatSelector(options: DownloadOptions): string | null {
  if (options.formatId) return options.formatId;
  if (options.mode === 'audio') return 'bestaudio/best';

  switch (options.quality) {
    case 'best':
      return 'bestvideo*+bestaudio/best';
    case 'best-compatible':
      return 'bestvideo[vcodec^=avc1]+bestaudio[acodec^=mp4a]/best[ext=mp4]/best';
    case 'smallest':
      return 'worstvideo*+worstaudio/worst';
    case 'custom':
      return null;
  }
}

/** Builds the subtitle-related flags. */
function subtitleArgs(options: DownloadOptions): string[] {
  const { subtitles } = options;
  if (!subtitles.download && !subtitles.embed) return [];

  const args: string[] = [];
  if (subtitles.download) args.push('--write-subs');
  if (subtitles.includeAutoGenerated) args.push('--write-auto-subs');
  if (subtitles.embed) args.push('--embed-subs');
  if (subtitles.languages.length > 0) {
    args.push('--sub-langs', subtitles.languages.join(','));
  }
  return args;
}

/** Builds the playlist-related flags. */
function playlistArgs(options: DownloadOptions): string[] {
  const { playlist } = options;
  if (!playlist.enabled) return ['--no-playlist'];

  const args = ['--yes-playlist'];
  if (playlist.maxItems !== null && playlist.maxItems > 0) {
    args.push('--playlist-end', String(playlist.maxItems));
  }
  if (playlist.skipExisting) {
    // Marker only: the Rust side rewrites this to an absolute path inside the
    // output directory, since a relative archive file would land in the GUI
    // process's unpredictable working directory.
    args.push('--download-archive', 'archive.txt');
  }
  if (playlist.reverse) args.push('--playlist-reverse');
  return args;
}

/** Builds the audio-extraction and post-processing flags. */
function audioArgs(options: DownloadOptions): string[] {
  if (options.mode !== 'audio') return [];

  const args = ['-x', '--audio-format', options.audioFormat];
  if (options.audioBitrateKbps !== null) {
    args.push('--audio-quality', `${options.audioBitrateKbps}K`);
  }
  return args;
}

/** Builds the authentication flags. */
function cookieArgs(options: DownloadOptions): string[] {
  const { cookies } = options;
  if (cookies.cookieFile) return ['--cookies', cookies.cookieFile];
  if (cookies.fromBrowser) return ['--cookies-from-browser', cookies.fromBrowser];
  return [];
}

/**
 * Resolves the output template, falling back to the playlist-aware default
 * when the user hasn't provided one.
 */
export function resolveOutputTemplate(options: DownloadOptions): string {
  if (options.outputTemplate) return options.outputTemplate;
  return options.playlist.enabled ? PLAYLIST_OUTPUT_TEMPLATE : DEFAULT_OUTPUT_TEMPLATE;
}

/**
 * Translates download options into the yt-dlp argument list (excluding the
 * output path, URL and progress flags, which the backend adds).
 *
 * Pure and deterministic — the same options always produce the same args,
 * which makes it straightforward to test.
 */
export function buildDownloadArgs(options: DownloadOptions): string[] {
  const args: string[] = [];

  const selector = formatSelector(options);
  if (selector) args.push('-f', selector);

  args.push(...playlistArgs(options));
  args.push(...audioArgs(options));
  args.push(...subtitleArgs(options));
  args.push(...cookieArgs(options));

  if (options.mode === 'video' && options.videoContainer) {
    args.push('--merge-output-format', options.videoContainer);
  }
  if (options.downloadThumbnail) args.push('--write-thumbnail');
  if (options.embedThumbnail) args.push('--embed-thumbnail');
  if (options.embedMetadata) args.push('--embed-metadata');
  if (options.rateLimit) args.push('--limit-rate', options.rateLimit);
  if (options.proxy) args.push('--proxy', options.proxy);
  if (options.timeoutSeconds !== null) {
    args.push('--socket-timeout', String(options.timeoutSeconds));
  }
  if (options.verbose) args.push('--verbose');

  return args;
}
